In [3]:
import pandas as pd
weather_data={'date':['01-10-2012','02-02-2012','03-05-2016'],'temperature':[10,13,'n.a.'],'windspeed':[1,2,3],'Event':['Rain','Sunny','summer']}
xx=pd.DataFrame(weather_data)
def convert_people_cell(cell):
    if cell=='n.a.':
        return '10'
    return cell
n='golla'
xx=convert_people_cell(n)
xx

'golla'

In [5]:
import pandas as pd
d={'a':[1],'b':[2],'c':[3],'d':[123]}
xx=pd.DataFrame(d)
xx

   a  b  c    d
0  1  2  3  123

In [9]:
n=int(input())
c=0
while True:
    if n>1:
        for i in range(2,n//2+1):
            if n%i==0:
                break
        else:
            c+=1
            if c==2:
                print(n)
                break
    n+=1

3

In [11]:
n=int(input())
c=0
while True:
    if n>1:
        for i in range(2,n//2+1):
            if n%i==0:
                break
        else:
            c+=1
            if c==2:
                print(n)
                break
    n+=1

3

In [8]:
import pandas as pd
xx=pd.read_csv("a.")
xx

FileNotFoundError: [Errno 2] No such file or directory: 'a.csv'

In [5]:
l=[1,2,3]
m=[2,3,4]
xx=list(map(lambda x,y:x+y,l,m))
xx

[3, 5, 7]

In [8]:
import pandas as pd
Indian_weather={'Name':['Golla','Vishnu','Yadav'],'temp':[1,2,3],'Wind':[1,2,3]}
xx=pd.DataFrame(Indian_weather)
xx

     Name  temp  Wind
0   Golla     1     1
1  Vishnu     2     2
2   Yadav     3     3

In [17]:
import pandas as pd
Indian_weathe={'Name':['Golla','Vishneu','Yadav'],'temp':[1,2,3],'Wind':[1,2,3]}
xx=pd.DataFrame(Indian_weathe)
xx

      Name  temp  Wind
0    Golla     1     1
1  Vishneu     2     2
2    Yadav     3     3

In [18]:
pd.concat([Indian_weather,Indian_weathe])

TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

In [1]:
# function that takes in string argument as parameter
def comp(PROMPT, MaxToken=50, outputs=3):
	# using OpenAI's Completion module that helps execute
	# any tasks involving text
	response = openai.Completion.create(
		# model name used here is text-davinci-003
		# there are many other models available under the
		# umbrella of GPT-3
		model="text-davinci-003",
		# passing the user input
		prompt=PROMPT,
		# generated output can have "max_tokens" number of tokens
		max_tokens=MaxToken,
		# number of outputs generated in one call
		n=outputs
	)
	# creating a list to store all the outputs
	output = list()
	for k in response['choices']:
		output.append(k['text'].strip())
	return output

In [3]:
a='abcd11gdf15hnnn678hh4'
import re
re.findall('\d+',a)

['11', '15', '678', '4']